:cs:
  :machines: '~/.colostate/machines.yml'
  :user: 'ride'
  :key: '~/.ssh/id_rsa'
  :alias:
    me: brazeau
    hpc:
      - coconuts
      - bananas
    labs:
      - 120
      - 215
      - 225
      - 325
  :commands:
    tmux: -t "(tmux attach || tmux)"
